package Day2;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class Day2{

    public static void part1(String fileName){
        
        final int MAX_RED = 12;
        final int MAX_GREEN = 13;
        final int MAX_BLUE = 14;


        String[] data = readFromFile(fileName);
        
        int total = 0;

        int index = 1;
        for( String line : data){

            String toberemoved = "Game "+(index)+": ";

            // filter excess data, game data is just each cleaned line
            String gameLine = line.substring( toberemoved.length() );
            String[] gameData = gameLine.split("; ");

            boolean combinationIsPossible = true;

            for(String s : gameData){

                String[] matchData = s.split(", ");

                for( String match : matchData ){

                    // separates each handful per match
                    // i classify a handful as the number and the colour
                    // example: 2 red
                    String[] handful = match.split(" ");
                    int number = Integer.valueOf(handful[0]);
                    String colour = handful[1];

                    // makes sure each colour is possible to reach
                    switch (colour) {    
                        case "red":
                            if ( number > MAX_RED ){
                                combinationIsPossible = false;
                            }
                            break;
                    
                        case "blue":
                            if ( number > MAX_BLUE ){
                                combinationIsPossible = false;
                            }
                            break;
                        case "green":
                            if ( number > MAX_GREEN ){
                                combinationIsPossible = false;
                            }
                            break;
                    }

                }
            }

            if( combinationIsPossible ){
                total += index;
            }

            index++;
        }

        System.out.println("Total: "+total);

    }

    public static void part2(String fileName){

        String[] data = readFromFile(fileName);
        
        int total = 0;

        int index = 1;
        for( String line : data){

            String toberemoved = "Game "+(index)+": ";

            // again more cleaning up
            String gameLine = line.substring( toberemoved.length() );
            String[] gameData = gameLine.split("; ");

            // sets a new minimum per game
            int minRed = 0;
            int minBlue = 0;
            int minGreen = 0;

            for(String s : gameData){
                String[] matchData = s.split(", ");

                for( String match : matchData ){
                    // more cleaning
                    String[] handful = match.split(" ");
                    int number = Integer.valueOf(handful[0]);
                    String colour = handful[1];

                    switch (colour) {
                        // finds the max number of colours per game
                        // which is the same as the min number of colours you'd need
                        // to make it possible
                        case "red":
                            if ( number > minRed ){
                                minRed = number;
                            }
                            break;
                    
                        case "blue":
                            if ( number > minBlue ){
                                minBlue = number;
                            }
                            break;
                        case "green":
                            if ( number > minGreen ){
                                minGreen = number;
                            }
                            break;
                    }

                }

                
            }
            // calculate the "power" 🤓 of the game  
            int gamePower = minRed * minGreen * minBlue;
            total += gamePower; 

            index++;
        }
        System.out.println("Total: "+total);
    }

    
    // autogenerated by ChatGPT, dont even ask how it works
    public static String[] readFromFile(String fileName) {
       List<String> lines = new ArrayList<>();
       try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
           String line;
           while ((line = br.readLine()) != null) {
               lines.add(line);
           }
       } catch (IOException e) {
           e.printStackTrace();
       }
       return lines.toArray(new String[0]);
    }
    

    public static void main(String[] args) {
        String filename = "day2.txt";
        part2( filename );
    }

}